apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-load-generator
  namespace: ai4k8s-test
  labels:
    app: http-load-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-load-generator
  template:
    metadata:
      labels:
        app: http-load-generator
    spec:
      containers:
      - name: web-server
        # Use a simple HTTP server that can handle requests and generate CPU load
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: http-load-generator
  namespace: ai4k8s-test
spec:
  selector:
    app: http-load-generator
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: ClusterIP

