apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-autoscaling
  namespace: ai4k8s-test
  labels:
    app: test-app-autoscaling
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app-autoscaling
  template:
    metadata:
      labels:
        app: test-app-autoscaling
    spec:
      containers:
      - name: app
        image: python:3.11-slim
        command:
        - python
        - -c
        - |
          from http.server import HTTPServer, BaseHTTPRequestHandler
          import threading
          import time
          import os
          
          class LoadHandler(BaseHTTPRequestHandler):
              def do_GET(self):
                  if self.path == '/health':
                      self.send_response(200)
                      self.send_header('Content-type', 'text/plain')
                      self.end_headers()
                      self.wfile.write(b'OK')
                  elif self.path == '/cpu-load':
                      # Generate CPU load
                      duration = int(os.getenv('CPU_DURATION', '10'))
                      self.send_response(200)
                      self.send_header('Content-type', 'text/plain')
                      self.end_headers()
                      start = time.time()
                      while time.time() - start < duration:
                          _ = sum(range(1000))
                      self.wfile.write(f'Generated CPU load for {duration}s'.encode())
                  else:
                      self.send_response(200)
                      self.send_header('Content-type', 'text/html')
                      self.end_headers()
                      html = '''
                      <html>
                      <head><title>Test App for Autoscaling</title></head>
                      <body>
                      <h1>Test App for Autoscaling</h1>
                      <p>This app is used for testing HPA, Predictive, and Scheduled Autoscaling.</p>
                      <p><a href="/cpu-load">Generate CPU Load</a></p>
                      <p><a href="/health">Health Check</a></p>
                      </body>
                      </html>
                      '''
                      self.wfile.write(html.encode())
              
              def log_message(self, format, *args):
                  pass  # Suppress logging
          
          # Background CPU load generator (adjustable via env var)
          def background_load():
              cpu_percent = float(os.getenv('CPU_LOAD_PERCENT', '30'))
              while True:
                  work_time = cpu_percent / 100.0
                  sleep_time = 1.0 - work_time
                  start = time.time()
                  while time.time() - start < work_time:
                      _ = sum(range(1000))
                  time.sleep(sleep_time)
          
          # Start background load generator
          load_thread = threading.Thread(target=background_load, daemon=True)
          load_thread.start()
          
          # Start HTTP server
          server = HTTPServer(('0.0.0.0', 8080), LoadHandler)
          print('Server running on port 8080')
          server.serve_forever()
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        env:
        - name: CPU_LOAD_PERCENT
          value: "30"  # Default 30% CPU load
        - name: CPU_DURATION
          value: "10"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-autoscaling
  namespace: ai4k8s-test
spec:
  selector:
    app: test-app-autoscaling
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP

