---
apiVersion: v1
kind: Service
metadata:
  name: compute
  namespace: default
  labels:
    app: compute
    app.kubernetes.io/part-of: mubench-multiclass
spec:
  type: ClusterIP
  selector:
    app: compute
  ports:
  - port: 8080
    targetPort: 8080
    name: http
